# Generated by Django 3.1.5 on 2021-06-22 12:27

from django.db import migrations, models
import django.utils.timezone
import tracking_details.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Package_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker', models.CharField(blank=True, default=tracking_details.models.id_genarator, max_length=7, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(default='None Added', max_length=50)),
                ('content', models.CharField(default='i-Phone12, D&G Designers Hand Bag', max_length=100)),
                ('date_pushed', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(default=tracking_details.models.limit_day)),
                ('progress', models.IntegerField(default=tracking_details.models.next_day)),
                ('current_location', models.CharField(max_length=20)),
            ],
        ),
    ]
