# Generated by Django 3.1.5 on 2021-06-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_details', '0003_user_package_detail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_package_detail',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('delayed', 'delayed'), ('waiting comfirmation', 'waiting comfirmation')], default=3, max_length=21),
        ),
    ]
